version: '3.7'
services:
  mongo:
    image: mongo:4.2.3
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: project

volumes:
    mongo_data:
